# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
remove_extra_newlines = true
format_docstrings = true
align_assignment = true
align_struct_field = true
align_pair_arrow = true
align_matrix = true
always_for_in = true